FROM node:18

WORKDIR /client

RUN npm install -g serve

COPY package*.json ./

RUN npm install --only=production

COPY build/ ./build/

RUN chmod -R 755 /client

EXPOSE 8080

CMD ["serve", "-s", "build"]



